### ISSUE TITLE
Port to ppxlib

### ISSUE THREAD

**Issue by XVilka** [ocaml-ppx/ppx_deriving_yojson#103]
To reduce the maintenance needed for upgrading the compiler version.
See also https://github.com/ocaml-ppx/ppx_deriving/issues/203 and https://github.com/ocaml-ppx/ppx_deriving_protobuf/issues/28

**Comment by gasche** [comment]
[ppx_yojson_conv](https://github.com/janestreet/ppx_yojson_conv) partly fits the bill, but it's not compatible with existing users of `ppx_deriving_yojson` so it's not exactly a Ppxlib port. (If there was a mode that exposes the same interface, I would be happy to recommend that our users switch.) At least it may be a good idea to look at their code and try to reuse some of it when trying to do a ppxlib port -- cc @thierry-martinez.

**Comment by XVilka** [comment]
See https://github.com/ocaml-ppx/ppx_deriving/pull/206

**Comment by XVilka** [comment]
Now it's fixed, should be the part of the next release.
