### ISSUE TITLE
Outdated function in docs

### ISSUE THREAD

**Issue by linse** [ocaml-ppx/ppx_deriving_yojson#105]
Hi, thanks for your library, I tried to use
`val ty_of_yojson_exn : Yojson.Safe.t -> ty`
but it does not work for me. The other functions work. I think the docs need an update.
Have a good day! :)

**Comment by gasche** [comment]
Thanks! I fixed the documentation -- you have to explicitly pass the option `{ exn = true }` to also get that function generated.
