### ISSUE TITLE
Fails to build on OCaml 4.11 because Pconst_string added an extra Loc.t parameter

### ISSUE THREAD

**Issue by rwmjones** [ocaml-ppx/ppx_deriving_yojson#116]
```
+ dune build -j48
File "ppx_deriving_yojson.cppo.ml", line 388, characters 39-72:
Error: The constructor Pconst_string expects 3 argument(s),
       but is applied here to 2 argument(s)
```

**Comment by rwmjones** [comment]
This is the downstream patch I have applied to work around this:
https://src.fedoraproject.org/rpms/ocaml-ppx-deriving-yojson/blob/master/f/ocaml-411.patch

**Comment by XVilka** [comment]
Will be solved by https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/118

**Comment by XVilka** [comment]
Should be closed, I think because of https://github.com/ocaml-ppx/ppx_deriving_yojson/commit/d06711479564486554aa0834fe900ac27d55ccc4
cc @thierry-martinez @gasche

**Comment by gasche** [comment]
Thanks for the triaging help, I will close indeed.
