### ISSUE TITLE
Derivation of json schemas

### ISSUE THREAD

**Issue by disteph** [ocaml-ppx/ppx_deriving_yojson#137]
Feature request:
I'd be interested in automatically generating a json schema (in the sense of [https://json-schema.org](https://json-schema.org)) out of an OCaml type definition. A json schema is describing a subset of all jsons and can be seen as a json type or a validity criterion on a json structure. Say if I have an OCaml type `ty = ... [@@deriving yojson]`, the json structures produced by `ty_to_yojson`, when applied to OCaml values of type `ty`, would be json structures abiding by the schema.

Ideally the schema would capture exactly the image of `ty_to_yojson`, but I expect the notion of json schema to be less expressive than OCaml's type system (e.g., I don't think json schemas have polymorphism and I think that in a json schema, all elements of JSON arrays must have the same type --which would be problematic for the encoding of OCaml's tuples as json arrays)...
...so for the moment what would be enough is producing a json schema that captures the image of `ty_to_yojson` for a simple class of OCaml types `ty` (no tuples, all constructors have "record-like / named arguments", etc), and perhaps producing a reasonable superset of that image when `ty` is outside that class.

I had hoped that the `meta` option of this deriver would do something along those lines, but it seems it does something much simpler. 
Has anybody heard of a project doing what I'd like?
- Json_schema in [ocplib-json-typed](https://github.com/OCamlPro/ocplib-json-typed) has a representation of schemas (which are themselves jsons) but I see no deriver;
- [ATD](https://atd.readthedocs.io/en/latest/index.html) offers its own notion of json type (from what I understand), whose expressivity may be well-suited to my use case, but the tool seems to offer a one way street towards OCaml code generation, while I need the reverse direction: producing json schemas from types in existing OCaml code;
- [ppx_yojson_conv](https://github.com/janestreet/ppx_yojson_conv) seems to be the same kind of ppx deriver as ppx_deriving_yojson and, just like [Milk](https://jaredforsyth.com/posts/announcing-milk/), they both seem to offer value-level serialization/deserialization while I need type-level "serialization";
- [ppx_yojson](https://github.com/NathanReb/ppx_yojson) does something different (though very useful).

**Comment by gasche** [comment]
My understanding is that `ppx_yojson_conv` is a more recent library that supersedes `ppx_deriving_yojson`, and is more actively maintained. Given that your feature requires new developments, I would go ask the ppx_yojson_conv developers.

(I will edit the README here to formalize this recommandation.)

**Comment by disteph** [comment]
Makes sense; I've posted my query [here](https://github.com/janestreet/ppx_yojson_conv/issues/4). Thanks!
