### ISSUE TITLE
Release v3.6.2

### ISSUE THREAD

**Issue by sim642** [ocaml-ppx/ppx_deriving_yojson#141]
PR #140 fixed multiple issues, so it would be nice to have a new release on opam-repository such that other packages depending on those fixes could also be published.

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/ocaml-ppx/ppx_deriving_yojson/commit/ae17630e97220292b9daf613e3bcadd8593f45f3

**Comment by sim642** [comment]
Thanks!
