### ISSUE TITLE
Allowing extra fields

### ISSUE THREAD

**Issue by davisuga** [ocaml-ppx/ppx_deriving_yojson#147]
Is it possible to ignore extra fields? With ppx_yojson_conv you just need to add a [@@yojson.allow_extra_fields].

**Comment by hcarty** [comment]
It is - `[@@deriving yojson { strict = false }]` will ignore extra fields. https://github.com/ocaml-ppx/ppx_deriving_yojson#semantics covers more at the end of the section.
