### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ppx_deriving_yojson#21]
I'm not sure how simple these are to fix, but it would be nice to either fix what is causing the warnings or, if it's possible, silence the warnings with the equivalent of appropriate `[@@warnings ...]` attributes.

Examples from utop:

```
utop # #warnings "A";;
utop # type t = { foo : string; bar : string } [@@deriving yojson];;
Characters 0-59:
Warning 39: unused rec flag.
type t = { foo : bytes; bar : bytes; }
val to_yojson : t -> Yojson.Safe.json = <fun>
val of_yojson : Yojson.Safe.json -> [> `Error of bytes | `Ok of t ] = <fun>

utop # type tt = A | B [@@deriving yojson];;
Characters 0-35:
Warning 39: unused rec flag.
Characters 0-35:
Warning 33: unused open Ppx_deriving_yojson_runtime.
type tt = A | B
val tt_to_yojson : tt -> Yojson.Safe.json = <fun>
val tt_of_yojson : Yojson.Safe.json -> [> `Error of bytes | `Ok of tt ] = <fun>
```

**Comment by whitequark** [comment]
I think @c-cube did similar fixes for ppx_deriving...

**Comment by c-cube** [comment]
I'm not sure I got the fix right, but yeah, maybe adding `[@@ocaml.warning "-39"]`
to the output of ppx_deriving would help.

**Comment by whitequark** [comment]
There's still `unused rec flag`, so reopening.

**Comment by emillon** [comment]
OK I'll update this.

**Comment by emillon** [comment]
It's actually completely independent, since this `rec` is added to the structure declaration themselves. I tried to add a `[@ocaml.warning "-39"]` to individual declarations, but the warning stays. It does not seem possible to attach an attribute to a whole `Pstr_value`, only to declarations or the whole module.

**Comment by sgrove** [comment]
We're running into this as well - is there any solution for us other than disabling the warning entirely?

**Comment by whitequark** [comment]
Hm, I'm not sure. @c-cube ?

**Comment by vgrocha** [comment]
Hey guys, any updates on this issue?

**Comment by emillon** [comment]
It's possible to generate code like this to wrap the suppression within a given scope, maybe that's a viable solution.

```ocaml
include struct
  [@@@ warning "-39"]

  (* ... put declarations here ... *)
end
```

**Comment by whitequark** [comment]
> Hey guys, any updates on this issue?

I will not be implementing a fix for the warnings.

**Comment by emillon** [comment]
I'm not sure what you mean - would you accept a PR that fixes them, though?

**Comment by whitequark** [comment]
> would you accept a PR that fixes them, though?

Of course, I will.

**Comment by stevebleazard** [comment]
PR #68 fixed this and a couple of other warnings so I think this PR can be closed without a merge
