### ISSUE TITLE
`[%to_yojson: int list]` gives `'a list -> ...`

### ISSUE THREAD

**Issue by vogler** [ocaml-ppx/ppx_deriving_yojson#52]
Is there a reason why this is polymorphic?

~~~ocaml
utop # [%to_yojson: int list] ["oh"; "no"]
- : [> `List of [> `Int of string ] list ] = `List [`Int "oh"; `Int "no"]
~~~

Version 3.0

**Comment by whitequark** [comment]
No reason other than me not placing an explicit constraint. Actually I'm not sure I understand why it works that way at all.
