### ISSUE TITLE
Enhancement request: of_yojson throw runtime exception rather than return result

### ISSUE THREAD

**Issue by tomjridge** [ocaml-ppx/ppx_deriving_yojson#57]
This would be useful in cases where it is known that the json is of the right format, i.e., the exception will not in fact be thrown. Possibly also useful if you prefer exceptions to results (perhaps there are a few situations where an exception is the right choice?)

**Comment by hcarty** [comment]
Two (relatively) simple ways this could be added.  One is to add an option within the annotation to specify if you want the exception-raising or the `result`-returning version.  Another is to generate two functions (`of_yojson` and `of_yojson_exn`).

For now, if you want to assume the format is correct or directly convert the `result` to an exception if it's an `Error` you can use something like http://erratique.ch/software/rresult/doc/Rresult.R.html#VALget_ok

**Comment by tomjridge** [comment]
I guess I probably prefer the of_yojson_exn version rather than the annotation. For the moment I am just pattern matching on the result which is not a big issue really.

**Comment by whitequark** [comment]
PR for of_yojson_exn will be accepted.

**Comment by stevebleazard** [comment]
This can now be closed as #68 resolved this
