### ISSUE TITLE
Unbound value `to_json`.

### ISSUE THREAD

**Issue by dannywillems** [ocaml-ppx/ppx_deriving_yojson#58]
I try with a simple code:
```shell
mkdir /tmp/test_jbuilder/
touch /tmp/test_jbuilder/test.opam
touch /tmp/test_jbuilder/test.ml
touch /tmp/test_jbuiler/jbuild
```

I have these lines in the jbuild file.
```
(library
 ((name        test)
  (public_name test)
  (modules (test))
  (preprocess (pps (ppx_deriving ppx_deriving_yojson ppx_driver.runner -no-check)))
  (libraries (ppx_deriving ppx_deriving_yojson yojson))))
```
And these lines in the `test.ml` file.
```
type t = {hello: string} [@@deriving yojson]
let t = to_yojson {hello = "test"}
```

When using `jbuilder build @install`, I have the following error:
```
    ocamlopt .ppx/ppx_deriving+ppx_deriving_yojson+ppx_driver.runner/ppx.exe
         ppx test.pp.ml
    ocamldep test.depends.ocamldep-output
      ocamlc test.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/danny/.opam/ocaml-4.04.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/danny/.opam/ocaml-4.04.0/lib/biniou -I /home/danny/.opam/ocaml-4.04.0/lib/easy-format -I /home/danny/.opam/ocaml-4.04.0/lib/ocaml -I /home/danny/.opam/ocaml-4.04.0/lib/ocaml-migrate-parsetree -I /home/danny/.opam/ocaml-4.04.0/lib/ocaml/compiler-libs -I /home/danny/.opam/ocaml-4.04.0/lib/ppx_derivers -I /home/danny/.opam/ocaml-4.04.0/lib/ppx_deriving -I /home/danny/.opam/ocaml-4.04.0/lib/ppx_deriving_yojson -I /home/danny/.opam/ocaml-4.04.0/lib/ppx_tools -I /home/danny/.opam/ocaml-4.04.0/lib/result -I /home/danny/.opam/ocaml-4.04.0/lib/yojson -no-alias-deps -I . -o test.cmo -c -impl test.pp.ml)
File "test.ml", line 2, characters 8-17:
Error: Unbound value to_yojson
```

Of course, I tried with `t_to_yosjon` but it doesn't work.
```

**Comment by emillon** [comment]
Indeed, that should work. The solution from [this comment](https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/49#issuecomment-320978526) works: adding `true: linkall` fixes this issue.

**Comment by maelvalais** [comment]
In 517a535e624186c20db555e576c0539c66b27ddf, the `true: linkall` has been added. To use this version (master):
    
    opam pin add ppx_deriving_yojson --dev-repo

**Comment by rauanmayemir** [comment]
@dannywillems did you find a solution to the issue?
I'm using latest v3.1 with jbuilder config similar to yours.

If I set `ppx_deriving_yojson` in pps, I keep having `Warning 39: unused rec flag`.
And if I leave only `ppx_deriving`, I get `Error: Unbound value of_yojson` (or mytype_of_yojson).

**Comment by gasche** [comment]
@dannywillems, does using the latest versions of ppx_deriving and jbuilder and ppx_driver fix your issues?

**Comment by rgrinberg** [comment]
Having the latest ppx_type_conv is critical here as well.

**Comment by emillon** [comment]
`ppx_type_conv.v0.9.1` is only available on OCaml >= 4.04. I seem to recall that because one of its dependencies, `ppx_driver.v0.9.2` is only available on >= 4.05. Is there a solution to continue supporting older compiler versions?

**Comment by diml** [comment]
@emillon `ppx_type_Conv.v0.9.1` depends on `ppx_driver >= "v0.9"`, so that shouldn't be the issue

**Comment by emillon** [comment]
@diml I'll try to reduce the problem, which is tough since there are many packages involved. On which repository can I open an issue?

**Comment by diml** [comment]
you can open it on `ppx_type_conv`

**Comment by dannywillems** [comment]
Everything is OK now with the last versions. Thanks.
