### ISSUE TITLE
Deriving with ocaml 4.05

### ISSUE THREAD

**Issue by kmicinski** [ocaml-ppx/ppx_deriving_yojson#63]
```
kmicinski-17:symdroid kmicinski$ opam install -y ppx_deriving_yojson
The following dependencies couldn't be met:
  - ppx_deriving_yojson -> ppx_deriving < 3.0
Your request can't be satisfied:
  - ppx_deriving<1.0 is not available because your system doesn't comply with ocaml-version >= "4.02.0" & ocaml-version < "4.03".
  - ppx_deriving<2.0 is not available because your system doesn't comply with ocaml-version = "4.02.1" & ocaml-version < "4.03" & opam-version >= "1.2".
  - ppx_deriving<3.0 is not available because your system doesn't comply with ocaml-version >= "4.02.2" & ocaml-version < "4.03" & opam-version >= "1.2".
```

This confuses me, because if I'm reading the other issues correctly, it appears that I should be able to install.

**Comment by emillon** [comment]
Just to be sure, did you run `opam update` before?

**Comment by kmicinski** [comment]
Yes, and this happened on two separate builds, a Linux and MacOS machine. We eventually downgraded the OCaml version.

**Comment by mindbound** [comment]
I'm also getting the same error. What are the reasons that prevent ppx_deriving_yojson to be updated for 4.05?

**Comment by whitequark** [comment]
Maintainer overload.

**Comment by mindbound** [comment]
That's understandable. Thank you for the quick response.

**Comment by slel** [comment]
Note: this prevents installing [the "ocaml-jupyter" Jupyter kernel for OCaml](https://github.com/akabe/ocaml-jupyter) with OCaml 4.05.
See https://github.com/akabe/ocaml-jupyter/issues/52#issuecomment-333112779.

**Comment by mindbound** [comment]
This also prevents [Kremlin](https://github.com/FStarLang/kremlin) to be compiled with OCaml 4.05.

**Comment by stevebleazard** [comment]
4.05 and 4.06 now install without issue. This can be closed
