### ISSUE TITLE
Associative lists as JSON objects

### ISSUE THREAD

**Issue by andrenth** [ocaml-ppx/ppx_deriving_yojson#73]
Hi

Is there a way to get an associative list to be converted to a JSON object instead of an array of arrays, similarly to atdgen's `<json repr="object">`?

**Comment by whitequark** [comment]
Nope!

**Comment by andrenth** [comment]
Is there a workaround? In many situations the JSON object has arbitrary keys, so defining a record is not possible.

**Comment by whitequark** [comment]
Define a newtype and manually implement `of_yojson` and `to_yojson` functions for it.

**Comment by andrenth** [comment]
Got it, thanks.
