### ISSUE TITLE
Update opam

### ISSUE THREAD

**Issue by bluddy** [ocaml-ppx/ppx_deriving_yojson#94]
Version 3.3 constrains yojson to < 1.6.0, which means only ocaml <= 4.06.0 is supported. Please release a version to opam that opens up this constraint.

**Comment by AlexKnauth** [comment]
For a temporary workaround until the next release, you can pin the repository:
https://github.com/ocaml-ppx/ppx_deriving_yojson/issues/93#issuecomment-460398487

**Comment by fare** [comment]
Can ppx_deriving_yojson make a release, even a minor release, so as to unbreak opam?

**Comment by NathanReb** [comment]
@bluddy could you further explain why that means `ocaml<=4.06.0`? Neither `ppx_deriving_yojson` nor `yojson` seem to have an upper bound on the ocaml version, maybe I'm missing something.

@gasche a release would indeed be nice, I'm happy to help with `ppx_deriving_yojson` if you need some!

**Comment by gasche** [comment]
I now have pre-releases of [ppx_deriving](https://github.com/ocaml/opam-repository/pull/13652) and [ppx_deriving_yojson](https://github.com/ocaml/opam-repository/pull/13653) in the opam-repository pipeline. These are not releases yet, I want to look at the reverse-dependencies (revdeps) CI reports to see the affect on users. If this goes well, the release should be soon; but help to triage the revdeps failure could be helpful.

**Comment by XVilka** [comment]
WIP PR is here https://github.com/ocaml/opam-repository/pull/14018

**Comment by NathanReb** [comment]
I'm releasing a new version of `Yojson`, reverting the deprecation warning which brought nothing but trouble so far.

That should solve it until a new version of `ppx_deriving_yojson` is released.

See https://github.com/ocaml/opam-repository/pull/14090

**Comment by AlexKnauth** [comment]
Now that https://github.com/ocaml/opam-repository/pull/14259 is in and version 3.4 is released on Opam, is this issue resolved?

**Comment by gasche** [comment]
Yes -- for the time being. The thing with releases is that you are always late for the next one ;-)
